---
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50
ratings:
  paths:
  - "**.js"
exclude_paths:
- node_modules/
- test/
- public/